import { expect, open, test, uniqueEmail } from './fixtures'

test('home shows the promise, catalog entry points and structured data', async ({ page }) => {
  await open(page, '/')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('stilul')
  const ld = await page.locator('script[type="application/ld+json"]').allTextContents()
  expect(ld.join('')).toContain('"Optician"')
  await page.getByRole('link', { name: /Rame de vedere/ }).first().click()
  await expect(page).toHaveURL(/\/rame-de-vedere/)
})

test('catalog filters by real lens width and keeps it in the URL', async ({ page }) => {
  await open(page, '/rame-de-vedere')
  const cards = page.locator('main article')
  const before = await cards.count()
  await page.locator('aside[aria-label=Filtre] summary', { hasText: 'Dimensiuni exacte' }).click()
  const min = page.getByLabel('Lățime lentilă minim').locator('visible=true')
  await min.fill('53')
  await min.press('Enter')
  await expect(page).toHaveURL(/lentila-min=53/)
  await expect.poll(async () => cards.count()).toBeLessThan(before)
})

test('product page: true dimensions, price and ProductGroup data', async ({ page }) => {
  await open(page, '/rame/mira-52')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Mira 52')
  await expect(page.getByText('52', { exact: false }).first()).toBeVisible()
  const ld = (await page.locator('script[type="application/ld+json"]').allTextContents()).join('')
  expect(ld).toContain('"ProductGroup"')
  expect(ld).toContain('/imagini/rame/mira-52/')
})

test('configurator → cart → checkout with cash on delivery', async ({ page }) => {
  await open(page, '/configurator/mira-52')
  await page.getByLabel('SPH OD').selectOption('-2.25')
  await page.getByLabel('CYL OD').selectOption('-0.75')
  await page.getByLabel('Ax OD').fill('180')
  await page.getByLabel('SPH OS').selectOption('-2')
  await page.getByRole('button', { name: 'Adaugă în coș' }).click()
  await page.waitForURL('**/cos**')
  await expect(page.getByText('Rețetă completată')).toBeVisible()
  await page.getByRole('link', { name: /Finalizează comanda/ }).click()
  await page.waitForURL('**/checkout')
  await page.locator('#f-firstName').fill('Ana')
  await page.locator('#f-lastName').fill('Testescu')
  await page.locator('#f-email').fill(uniqueEmail('ana'))
  await page.locator('#f-phone').fill('0722 123 456')
  await page.locator('#f-street').fill('Str. Domnească 10')
  await page.locator('#f-city').fill('Galați')
  await page.locator('#f-county').selectOption('Galați')
  await page.getByRole('radio', { name: /Ramburs/ }).click()
  await page.locator('input[name=terms]').check({ force: true })
  await page.locator('input[name=healthConsent]').check({ force: true })
  await page.getByRole('button', { name: 'Plasează comanda' }).click()
  await page.waitForURL('**/comanda/**')
  await expect(page.getByText('Mulțumim, Ana!')).toBeVisible()
})

test('checkout refuses an order without accepting the terms', async ({ page }) => {
  await open(page, '/rame/iris-49')
  await page.getByRole('button', { name: 'Doar rama' }).click()
  await expect(page.getByText('Adăugat în coș.')).toBeVisible()
  await open(page, '/checkout')
  await page.locator('#f-firstName').fill('Ion')
  await page.locator('#f-lastName').fill('Fără')
  await page.locator('#f-email').fill(uniqueEmail('ion'))
  await page.locator('#f-phone').fill('0744000111')
  await page.getByRole('radio', { name: /Ridicare din showroom/ }).click()
  await page.getByRole('button', { name: /Plasează comanda|Plătește/ }).click()
  await expect(page).toHaveURL(/\/checkout/)
})
